CREATE TABLE subjects (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL,
curricula VARCHAR(30),
standard VARCHAR(30)
);

CREATE TABLE curricula (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
subject_id INTEGER,
CONSTRAINT fk_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE SET NULL
);

CREATE TABLE students (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
last_name VARCHAR(30) NOT NULL,
first_name VARCHAR(30) NOT NULL,
grade VARCHAR(50) NOT NULL,
);

CREATE TABLE assignments (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
complete BOOLEAN,
curricula DECIMAL,
subject_id INTEGER,
student_id INTEGER,
CONSTRAINT fk_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE SET NULL,
CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES students(id)
);
