CREATE TABLE subjects (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL,
curricula VARCHAR(30),
standard VARCHAR(30)
);

CREATE TABLE curricula (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
subject VARCHAR(30)
);

CREATE TABLE student (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
last_name VARCHAR(30) NOT NULL,
first_name VARCHAR(30) NOT NULL,
grade VARCHAR(50) NOT NULL,
);

CREATE TABLE assignments (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
curricula DECIMAL,
subject VARCHAR(30) NOT NULL,
student VARCHAR(30) NOT NULL,
complete BOOLEAN
-- CONSTRAINT fk_subjects FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE SET NULL,
-- CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE SET NULL
);
